contractions_dict = {
    "ain't": "am not",
    "aint": "am not",
    "aren't": "are not",
    "arent": "are not",
    "b/c": "because",
    "b'cause": "because",
    "bcause": "because",
    "b'coz": "because",
    "bcoz": "because",
    "c/i": "check in",
    "could've": "could have",
    "couldve": "could have",
    "couldn't": "could not",
    "couldnt": "could not",
    "couldn't've": "could not have",
    "couldntve": "could not have",
    "can't": "cannot",
    "cant": "cannot",
    "doin'": "doing",
    "doin": "doing",
    "didn't": "did not",
    "didnt": "did not",
    "doesn't": "does not",
    "doesnt": "does not",
    "don't": "do not",
    "dont": "do not",
    "dunno": "do not know",
    "gimme": "give me",
    "goin'": "going",
    "goin": "going",
    "gonna": "going to",
    "how'll": "how will",
    "howll": "how will",
    "he'd've": "he would have",
    "hadn't've": "had not have",
    "haven't": "have not",
    "havent": "have not",
    "hasn't": "has not",
    "hasnt": "has not",
    "hadn't": "had not",
    "hadnt": "had not",
    "how'd": "how did",
    "howd": "how did",
    "how'd'y": "how do you",
    "he's": "he is",
    "hes": "he is",
    "he'd": "he would",
    "hed": "he would",
    "he'll": "he will",
    "hell": "he will",
    "he'll've": "he will have",
    "how's": "how is",
    "hows": "how is",
    "I'm": "I am",
    "Im": "I am",
    "I've": "I have",
    "Ive": "I have",
    "I'd": "I would",
    "Id": "I would",
    "I'll": "I will",
    "Ill": "I will",
    "I'll've": "I will have",
    "it'd": "it would",
    "itd": "it would",
    "it'll": "it will",
    "itll": "it will",
    "it'll've": "it shall have",
    "isn't": "is not",
    "isnt": "is not",
    "kinda": "kind of",
    "let's": "let us",
    "lets": "let us",
    "ma'am": "madam",
    "maam": "madam",
    "might've": "might have",
    "mightve": "might have",
    "must've": "must have",
    "mustve": "must have",
    "mightn't": "might not",
    "mightnt": "might not",
    "mightn't've": "might not have",
    "mustn't": "must not",
    "mustnt": "must not",
    "mayn't": "may not",
    "maynt": "may not",
    "mustn't've": "must not have",
    "nothin't": "nothing",
    "nothint": "nothing",
    "needn't": "need not",
    "neednt": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oclock": "of the clock",
    "oughta": "ought to",
    "oughtn't": "ought not",
    "oughtnt": "ought not",
    "oughtn't've": "ought not have",
    "p/nt": "per night",
    "should've": "should have",
    "shouldve": "should have",
    "shouldn't": "should not",
    "shouldnt": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "sove": "so have",
    "so's": "so is",
    "shan't": "shall not",
    "shant": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "somethin'": "something",
    "she'td've": "she would have",
    "she's": "she is",
    "shes": "she is",
    "she'd": "she had",
    "shed": "she had",
    "she'll": "she will",
    "shell": "she will",
    "she'll've": "she will have",
    "to've": "to have",
    "tove": "to have",
    "that'd've": "that would have",
    "that'd": "that had",
    "thatd": "that had",
    "that's": "that is",
    "thats": "that is",
    "there'd've": "there would have",
    "they'd've": "they would have",
    "they're": "they are",
    "theyre": "they are",
    "they've": "they have",
    "theyve": "they have",
    "they'll": "they will",
    "theyll": "they will",
    "they'll've": "they will have",
    "'tis": "it is",
    "tis": "it is",
    "there'd": "there would",
    "thered": "there would",
    "there's": "there is",
    "theres": "there is",
    "they'd": "they would",
    "theyd": "they would",
    "u": "you",
    "w/": "with",
    "w/a": "with a",
    "w/flat": "with flat",
    "wasn't": "was not",
    "wasnt": "was not",
    "wanna't": "want to",
    "wannat": "want to",
    "we'd've": "we would have",
    "we'll": "we will",
    "well": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "were": "we are",
    "we've": "we have",
    "weve": "we have",
    "weren't": "were not",
    "werent": "were not",
    "what're": "what are",
    "whatre": "what are",
    "what've": "what have",
    "whatve": "what have",
    "when've": "when have",
    "whenve": "when have",
    "where'd": "where did",
    "whered": "where did",
    "where've": "where have",
    "whereve": "where have",
    "who've": "who have",
    "whove": "who have",
    "why've": "why have",
    "whyve": "why have",
    "will've": "will have",
    "willve": "will have",
    "won't": "will not",
    "wont": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldve": "would have",
    "wouldn't": "would not",
    "wouldnt": "would not",
    "wouldn't've": "would not have",
    "we'd": "we would",
    "wed": "we would",
    "what'll": "what will",
    "whatll": "what will",
    "what'll've": "what will have",
    "what's": "what is",
    "whats": "what is",
    "when's": "when is",
    "whens": "when is",
    "where's": "where is",
    "wheres": "where is",
    "who'll": "who will",
    "wholl": "who will",
    "who'll've": "who will have",
    "who's": "who is",
    "whos": "who is",
    "why's": "why is",
    "whys": "why is",
    "y'all": "you all",
    "yall": "you all",
    "you're": "you are",
    "youre": "you are",
    "you've": "you have",
    "youve": "you have",
    "y'all'd": "you all would",
    "y'all've": "you all have",
    "y'all'd've": "you all would have",
    "you'd've": "you would have",
    "y'all're": "you all are",
    "you'd": "you would",
    "youd": "you would",
    "you'll": "you will",
    "youll": "you will",
    "you'll've": "you will have",
}

def fix(word):
    if word in contractions_dict:
        return contractions_dict[word]
    return word